package main

// Code generated by Chat-GPT3.5

import (
	"log"

	"github.com/spf13/cast"
	"github.com/xuri/excelize/v2"
)

func main() {
	// 打开原始Excel文件
	f, err := excelize.OpenFile("translate-todo.xlsx")
	if err != nil {
		log.Fatal(err)
	}

	// 创建新的Excel文件
	f2 := excelize.NewFile()

	// 复制第一个工作表的所有单元格和样式
	rows, err := f.GetRows("测试案例")
	if err != nil {
		log.Fatal(err)
	}
	for rowIndex, row := range rows {
		for columnIndex, cell := range row {
			axis, _ := excelize.CoordinatesToCellName(rowIndex+1, columnIndex+1)

			// 复制单元格的内容
			if err := f2.SetCellValue("Sheet1", axis, cell); err != nil {
				log.Fatal(err)
			}

			// 复制单元格的样式
			style, err := f.GetCellStyle("测试案例", axis)
			if err != nil {
				log.Fatal(err)
			}
			if err := f2.SetCellStyle("Sheet1", axis, axis, style); err != nil {
				log.Fatal(err)
			}
		}
	}

	// 复制原始文件的列宽度和行高度
	colWidths, err := f.GetCols("测试案例")
	if err != nil {
		log.Fatal(err)
	}
	for columnIndex, width := range colWidths {
		colIdx, _ := excelize.ColumnNumberToName(columnIndex + 1)
		if err := f2.SetColWidth("Sheet1", colIdx, colIdx, cast.ToFloat64(width)); err != nil {
			log.Fatal(err)
		}
	}
	rowHeights, err := f.GetRows("Sheet1")
	if err != nil {
		log.Fatal(err)
	}
	for rowIndex, height := range rowHeights {
		if err := f2.SetRowHeight("Sheet1", rowIndex+1, cast.ToFloat64(height)); err != nil {
			log.Fatal(err)
		}
	}

	// 保存新的Excel文件
	if err := f2.SaveAs("new.xlsx"); err != nil {
		log.Fatal(err)
	}
}
