// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/server-server.proto

package serverserver

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ServerServer service

func NewServerServerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ServerServer service

type ServerServerService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (ServerServer_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (ServerServer_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (ServerServer_BidiStreamService, error)
}

type serverServerService struct {
	c    client.Client
	name string
}

func NewServerServerService(name string, c client.Client) ServerServerService {
	return &serverServerService{
		c:    c,
		name: name,
	}
}

func (c *serverServerService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "ServerServer.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServerService) ClientStream(ctx context.Context, opts ...client.CallOption) (ServerServer_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "ServerServer.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serverServerServiceClientStream{stream}, nil
}

type ServerServer_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type serverServerServiceClientStream struct {
	stream client.Stream
}

func (x *serverServerServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serverServerServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *serverServerService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (ServerServer_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "ServerServer.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &serverServerServiceServerStream{stream}, nil
}

type ServerServer_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type serverServerServiceServerStream struct {
	stream client.Stream
}

func (x *serverServerServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serverServerServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverServerService) BidiStream(ctx context.Context, opts ...client.CallOption) (ServerServer_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "ServerServer.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serverServerServiceBidiStream{stream}, nil
}

type ServerServer_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type serverServerServiceBidiStream struct {
	stream client.Stream
}

func (x *serverServerServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serverServerServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *serverServerServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ServerServer service

type ServerServerHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, ServerServer_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, ServerServer_ServerStreamStream) error
	BidiStream(context.Context, ServerServer_BidiStreamStream) error
}

func RegisterServerServerHandler(s server.Server, hdlr ServerServerHandler, opts ...server.HandlerOption) error {
	type serverServer interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type ServerServer struct {
		serverServer
	}
	h := &serverServerHandler{hdlr}
	return s.Handle(s.NewHandler(&ServerServer{h}, opts...))
}

type serverServerHandler struct {
	ServerServerHandler
}

func (h *serverServerHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ServerServerHandler.Call(ctx, in, out)
}

func (h *serverServerHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ServerServerHandler.ClientStream(ctx, &serverServerClientStreamStream{stream})
}

type ServerServer_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type serverServerClientStreamStream struct {
	stream server.Stream
}

func (x *serverServerClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *serverServerHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ServerServerHandler.ServerStream(ctx, m, &serverServerServerStreamStream{stream})
}

type ServerServer_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type serverServerServerStreamStream struct {
	stream server.Stream
}

func (x *serverServerServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *serverServerHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ServerServerHandler.BidiStream(ctx, &serverServerBidiStreamStream{stream})
}

type ServerServer_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type serverServerBidiStreamStream struct {
	stream server.Stream
}

func (x *serverServerBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serverServerBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverServerBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverServerBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverServerBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *serverServerBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
